### ISSUE TITLE
Add over-write for Windows and Linux OS

### ISSUE THREAD

**Issue by Titan3301** [nwutils/create-desktop-shortcuts#54]
I'm creating a software with nodejs and I need to over-write shortcuts in it , I found nothing to read Data from a .lnk file else i would have used fs and did it, Could you please Try adding overwrite for windows or something which gives info of the shortcut.

**Comment by TheJaredWilcurt** [comment]
Deleting files is something that each file system sucks at in unique ways. I would recommend pulling in `fs-extra` and using it to delete the file first, then use `create-desktop-shortctuts`. `fs-extra` has tons of code to handle all the weird edgecases you run into when trying to delete a file. Also you don't need to check if the file exists first before using it. 

`npm install --save fs-extra create-desktop-shortcuts`

```js
function createWindowsShortcut () {
  // Because we only specify Windows code in this function,
  // there is no point to run it from other platforms
  if (process.platform !== 'win32') {
    return;
  }

  // Imports
  const path = require('path');
  const createDesktopShortcut = require('create-desktop-shortcuts');
  const fs = require('fs-extra');

  // Variables/settings
  const name = 'My App Name';
  const outputPath = 'C:\\some\\folder';
  const outputFile = path.join(outputPath, name + '.lnk');

  // If the file already exists, it will be deleted first
  fs.removeSync(outputFile);

  // This returns true if the shortcut was created successfully
  const created = createDesktopShortcut({
    windows: {
      filePath: 'C:\\path\\to\\executable.exe',
      outputPath,
      name
    }
  );

  // if there was an issue creating the shortcut, throw
  if (!created) {
    throw 'Shortcut failed to create';
  }
}

// because both the delete and create are synchronous, we use a try/catch
try {
  createWindowsShortcut();
} catch (err) {
  console.log('Failed to either delete the old shortcut or create the new one');
  console.error(err);
}
```

`fs-extra` is a pretty bulky dependency for me to pull in to this library, since this is the first time this has been requested since 2019, I'd prefer to not increase the library size if it's something most people don't need.

**Comment by Titan3301** [comment]
But I need to extract icon and file path of the previous shortcut too , how could I extract it?
________________________________

**Comment by TheJaredWilcurt** [comment]
So I think what you want is to:

1. Get properties from a shortcut
1. Delete the shortcut (that is what fs-extra does, seen above)
1. Create a new shortcut from the properties (that is what this library does)

So the problem is you are lacking a library to do step 1.

I think I can make that. gimme a day

**Comment by TheJaredWilcurt** [comment]
Okay, maybe less than a day. You can use this library now, and pair it with the code above.

* https://github.com/nwutils/get-windows-shortcut-properties
